Vagrant.configure("2") do |config|
  
  config.vm.define "webserver-01" do |svr|
    svr.vm.box = "debian/stretch64"
    svr.vm.network "public_network", bridge: "wlp1s0"
    svr.vm.network "private_network", ip: "192.168.100.10"
    svr.vm.network "forwarded_port", guest: 80, host: 8081
      svr.vm.provider "virtualbox" do |vb|
        vb.name = "webserver-01"
        vb.memory = 256
        vb.cpus = 1
      end
  end

  config.vm.define "webserver-02" do |svr|
   svr.vm.box = "debian/stretch64"
   svr.vm.network "public_network", bridge: "wlp1s0"
   svr.vm.network "private_network", ip: "192.168.100.20"
   svr.vm.network "forwarded_port", guest: 80, host: 8082
     svr.vm.provider "virtualbox" do |vb|
       vb.name = "webserver-02"
       vb.memory = 256
       vb.cpus = 1
     end
  end

  config.vm.define "loadbalance" do |svr|
   svr.vm.box = "debian/stretch64"
   svr.vm.network "public_network", bridge: "wlp1s0"
   svr.vm.network "private_network", ip: "192.168.100.254"
   svr.vm.network "forwarded_port", guest: 80, host: 8080
     svr.vm.provider "virtualbox" do |vb|
       vb.name = "loadbalance"
       vb.memory = 128
       vb.cpus = 1
     end
  end  

end
